### ISSUE TITLE
Choice between American and British English

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/vim-angry-reviewer#2]
Theoretically, user should be able to choose American or British english.
There is the *english* variable in main() that now defaults to 'american' but the algorithm can use 'british' as well. Need to find a way to either pass a variable like AngryReviewEnglish from the user or alternatively use a different command like AngryReviewerBritish.

**Comment by BlakeJC94** [comment]
Just figured out how to pass vimscript variables to python scripts, should have a nice solution to this soon

**Comment by anufrievroman** [comment]
Thank you, works great now.
